### ISSUE TITLE
csscss hanging/giving no output

### ISSUE THREAD

**Issue by haydenzone** [zmoazeni/csscss#91]
Hi, 

I'm not completely sure if this is a bug, or if I'm not doing something correct.

OS: OSX Yosemite 10.10 (tried on OSX Mavericks 10.9.5)
Ruby Version: ruby 2.0.0p481
CSSCSS Version: 1.3.3

Installation steps:
1) Install brew
2) brew install gem
3) gem install csscss

test.css: 
body { 
background-color: red;
}
body { 
background-color: red;
}

Command: 
csscss -v test.css 

Expected: Some indication that body has a duplicate tag
Actuall: nothing

Also,

When I try this command: 
csscss https://webassetimvu-a.akamaihd.net/asset/e78ffdf5a603e786/build/web3d/web3d-app.css
It just hangs.

It also hangs when I pull down the file and run it directly on that file.

When I kill the file, I get this call stack:
    from /Library/Ruby/Gems/2.0.0/gems/csscss-1.3.3/lib/csscss/redundancy_analyzer.rb:100:in `=='
    from /Library/Ruby/Gems/2.0.0/gems/csscss-1.3.3/lib/csscss/redundancy_analyzer.rb:100:in`block (2 levels) in redundancies'
    from /Library/Ruby/Gems/2.0.0/gems/csscss-1.3.3/lib/csscss/redundancy_analyzer.rb:99:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/csscss-1.3.3/lib/csscss/redundancy_analyzer.rb:99:in`block in redundancies'
    from /Library/Ruby/Gems/2.0.0/gems/csscss-1.3.3/lib/csscss/redundancy_analyzer.rb:97:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/csscss-1.3.3/lib/csscss/redundancy_analyzer.rb:97:in`each_with_index'
    from /Library/Ruby/Gems/2.0.0/gems/csscss-1.3.3/lib/csscss/redundancy_analyzer.rb:97:in `redundancies'
    from /Library/Ruby/Gems/2.0.0/gems/csscss-1.3.3/lib/csscss/cli.rb:40:in`execute'
    from /Library/Ruby/Gems/2.0.0/gems/csscss-1.3.3/lib/csscss/cli.rb:17:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/csscss-1.3.3/lib/csscss/cli.rb:200:in`run'
    from /Library/Ruby/Gems/2.0.0/gems/csscss-1.3.3/bin/csscss:4:in `<top (required)>'
    from /usr/bin/csscss:23:in`load'
    from /usr/bin/csscss:23:in `<main>'

Let me know if you have any other questions. Pretty slick tool and I'm excited to get it working!

Thanks,
Hayden

**Comment by aesnyder** [comment]
Any resolution on this? Different errors but similar results over here.

**Comment by btilford** [comment]
Same here on Ubuntu 15.10
